name: Auto CLA

on:
  pull_request:
    types: [opened]

jobs:
  cla-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run CLA check
        uses: your-organization/cla-action@v1
        with:
        # 配置你的CLA检查工具，例如使用CLA Assistant或其他第三方工具